### PR TITLE
Separate dealing with file input to a helper class

### LINKED ISSUE #112: Uploading images doesn't work in firefox(?)
```
"/app_configurator/restapi/appearance.py", line 74, in get_or_upload_image
[Tue May 23 13:55:26 2017] [error]     return JSONResponse(update_image(app_id, image_type, request.data['file']))
[Tue May 23 13:55:26 2017] [error]   File "/app_configurator/bizz/appearance.py", line 224, in update_image
[Tue May 23 13:55:26 2017] [error]     image = Image.open(uploaded_file.file)
[Tue May 23 13:55:26 2017] [error] AttributeError: 'unicode' object has no attribute 'file'
```

### PR DESCRIPTION
**Pull request by abom**
Event target property is different between browsers, e.g. event.srcElement and event.target.

Added a helper class to deal with this.
Any component that has a file input can extend FileSelector, and override onFileSelected, alongside using onFilePicked with e.g. change event of the file input.

Closes #112.

### CODE REVIEW

File: client/frameworks/rcc/util.ts [hunk 1]
```diff
@@ -48,6 +48,35 @@ export abstract class AbstractControlValueAccessor implements ControlValueAccess
   }
 }
 
+
+export abstract class FileSelector {
+
+  onFileSelected(file: File) {
```
Comment (lucasvanhalst) [inline client/frameworks/rcc/util.ts]: Could you make this and the `onMultiFilesSelected` method abstract? 
`abstract onFileSelected(file: File);` 
That way there are no empty methods here

Comment (abom) [inline client/frameworks/rcc/util.ts]: Yes, but this won't make it a must to implement those methods in the subclass?

Comment (lucasvanhalst) [inline client/frameworks/rcc/util.ts]: true, maybe we should just log something if the method isn't implemented or something but I'd make the onFileSelected method mandatory regardless
